versoion: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permission:
  - object: /home/ubunutu
    pattern: "**"
    owener: ubuntu
    group: ubuntu
    
hooks:
  ApplicationStop: 
    - location: scripts/kill_process.sh
      timeout: 100
      runas: ubuntu
  ApplicationStart:
    - location: scripts/sun_process.sh
      timeout: 3600
      runas: ubuntu
