pipeline {
    agent any
    
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    
    environment {
        AWS_CREDENTIAL_NAME = "awsEcrCredentials"
        REGI0N = "ap-northeast-2"
        ECR_REPOSITORY = "257307634175.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "std07-spring-petclinic/spring-petclinic"
        ECR_DOCKER_TAG = "1.0"
    }
    stages {
        stage('Git init') {
            steps {
                echo 'Git Init'
                git url:'https://github.com/wansohaneul/spring-petclinic.git',
                branch:'main', credentialsId: 'gitCredentials'
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
                sh 'mvn -Dmaven.test.failur.ignore=true clean package'
            }
        }
        stage('Docker Image Build') {
            steps {
                echo 'Docker Image Build'
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG} .' 
                } 
            }
        }
        stage('Docker Image Push') {
            steps {
                echo 'Docker Image Push'
                script {
                    // cleanup current user docker credentials
                    sh 'rm -f ~/.dockerfg ~/.docker/config.json || true'
                    
                    docker.withRegistry("https://${ECR_REPOSITORY}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                                        docker.image("${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG}")push()
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
